### ISSUE TITLE
GetValidMoves always returns empty List

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/ChessEngine#16]
The getValidMoves(Position from) function located in Engine always returns an Empty List
 - test able in current basic_mouse_input branch

**Comment by ToBinio** [comment]
After Updating to the newest Master Branch it now sometimes returns one but also throws sometimes (King) an IndexOutOfBounceException

**Comment by JonasPfeifer05** [comment]
Can u pls tell me at which call the index out of bound accurs?

**Comment by JonasPfeifer05** [comment]
As I started testing yesterday I found out why it almost always return an empty list. Will be fiyed soon.
