### ISSUE TITLE
Artifact not finding file

### ISSUE THREAD

**Issue by JonasPfeifer05** [JonasPfeifer05/ChessEngine#26]
Im currently trying to be able, to create a jar file to execute from the cmd, but whenever I start the jar it doesnt find the asset files. I created the artifact via -> File -> Project structure -> Artifacts -> + -> JAR -> From Module with dependencies -> MainClass = Main -> META-INF Directory = C:\dev\Private\ChessEngine\src\main\ -> Ok -> Added resources ordner

**Comment by ToBinio** [comment]
you need to use a extra gradle plugin for that... how exaclty i dont know....

**Comment by JonasPfeifer05** [comment]
Oke is it ok when we look at that together tomorrow if i dont find any solution?

**Comment by ToBinio** [comment]
https://stackoverflow.com/questions/21721119/creating-runnable-jar-with-gradle

**Comment by ToBinio** [comment]
https://stackoverflow.com/questions/24724383/add-resources-and-config-files-to-your-jar-using-gradle
