### ISSUE TITLE
Board.setup not Working

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/ChessEngine#8]
The Function setUp(int Player) in Board thows an "ArrayIndexOutOfBoundsException"
Testable in current GUI branch

**Comment by JonasPfeifer05** [comment]
Ok! Ill look in soon!

**Comment by JonasPfeifer05** [comment]
Can I just create a new branch to fix this problem? Can u then update your branch to use the newest master branch? Or how does it work?

**Comment by JonasPfeifer05** [comment]
Should be fixed and created a pull request to merge it into master
